name: Build Package

on:
  workflow_dispatch:

env:
  PKG_NAME: prometheus-node-exporter-lua-unbound
  PKG_ARCH: aarch64_cortex-a53

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # to create releases and upload artifacts
    steps:
      - uses: actions/checkout@v4

      - name: Get Package Version
        run: |
          PKG_VERSION=$(grep '^PKG_VERSION' ${{ env.PKG_NAME }}/Makefile | cut -d= -f2 | tr -d ' ')
          PKG_RELEASE=$(grep '^PKG_RELEASE' ${{ env.PKG_NAME }}/Makefile | cut -d= -f2 | tr -d ' ')
          echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV
          echo "PKG_RELEASE=$PKG_RELEASE" >> $GITHUB_ENV
          echo "PKG_TAG=$PKG_VERSION$([ $PKG_RELEASE != 1 ] && echo -$PKG_RELEASE || echo)" >> $GITHUB_ENV

      - name: Set SDK Architecture
        run: |
          echo "SDK_ARCH=${{ env.PKG_ARCH }}" >> $GITHUB_ENV

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ env.PKG_ARCH }}
          PACKAGES: ${{ env.PKG_NAME }}
          IGNORE_ERRORS: 1
          NO_DEFAULT_FEEDS: 1
          #INDEX: 1
          #V: s

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: bin/packages/${{ env.PKG_ARCH }}/action/*.apk

      - name: Force push tag
        run: |
          git tag -f ${{ env.PKG_TAG }}
          git push -f origin ${{ env.PKG_TAG }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.PKG_TAG }}
          name: "${{ env.PKG_TAG }}"
          files: bin/packages/${{ env.PKG_ARCH }}/action/*.apk

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: "packages"
          path: dist/

      - name: Rename apk file
        run: |
          mv dist/${{ env.PKG_NAME }}-*.apk dist/${{ env.PKG_NAME }}.apk

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
