name: Build Single Package
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add custom package
        run: |
          mkdir -p package/prometheus-node-exporter-lua-unbound
          cp -r prometheus-node-exporter-lua-unbound/* package/prometheus-node-exporter-lua-unbound/

      - name: Build Package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: aarch64_cortex-a53
          REPO: https://github.com/openwrt/openwrt.git
          BRANCH: openwrt-25.12
          MAKE_TARGET: package/prometheus-node-exporter-lua-unbound/{clean,compile}

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-package
          path: bin/packages/**/prometheus-node-exporter-lua-unbound-*.apk
